plugins {
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.148'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.mod_group_id

base {
	archivesName = 'media-hud-neoforge'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
	version = project.neo_version

	runs {
		client {
			client()
		}
	}

	mods {
		"${project.mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

processResources {
	inputs.property 'version', project.mod_version

	filesMatching('META-INF/neoforge.mods.toml') {
		expand 'version': project.mod_version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}
